// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMatchPlayer = `-- name: AddMatchPlayer :one
INSERT INTO match_players (
    match_id,
    user_id,
    player_index,
    score,
    is_winner,
    rating_before,
    rating_after
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, match_id, user_id, player_index, score, is_winner, rating_before, rating_after, created_at
`

type AddMatchPlayerParams struct {
	MatchID      pgtype.UUID `json:"match_id"`
	UserID       pgtype.UUID `json:"user_id"`
	PlayerIndex  int32       `json:"player_index"`
	Score        int32       `json:"score"`
	IsWinner     bool        `json:"is_winner"`
	RatingBefore int32       `json:"rating_before"`
	RatingAfter  int32       `json:"rating_after"`
}

func (q *Queries) AddMatchPlayer(ctx context.Context, arg AddMatchPlayerParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, addMatchPlayer,
		arg.MatchID,
		arg.UserID,
		arg.PlayerIndex,
		arg.Score,
		arg.IsWinner,
		arg.RatingBefore,
		arg.RatingAfter,
	)
	var i MatchPlayer
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.UserID,
		&i.PlayerIndex,
		&i.Score,
		&i.IsWinner,
		&i.RatingBefore,
		&i.RatingAfter,
		&i.CreatedAt,
	)
	return i, err
}

const completeMatch = `-- name: CompleteMatch :one
UPDATE matches
SET status = 'completed',
    winner_id = $2,
    ended_at = NOW(),
    duration_seconds = $3,
    metadata = $4
WHERE id = $1
RETURNING id, room_id, game_type, status, winner_id, started_at, ended_at, duration_seconds, metadata
`

type CompleteMatchParams struct {
	ID              pgtype.UUID `json:"id"`
	WinnerID        pgtype.UUID `json:"winner_id"`
	DurationSeconds int32       `json:"duration_seconds"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) CompleteMatch(ctx context.Context, arg CompleteMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, completeMatch,
		arg.ID,
		arg.WinnerID,
		arg.DurationSeconds,
		arg.Metadata,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameType,
		&i.Status,
		&i.WinnerID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Metadata,
	)
	return i, err
}

const createGameResult = `-- name: CreateGameResult :one
INSERT INTO game_results (
    match_id,
    game_type,
    rounds_played,
    summary
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, match_id, game_type, rounds_played, summary, created_at
`

type CreateGameResultParams struct {
	MatchID      pgtype.UUID `json:"match_id"`
	GameType     string      `json:"game_type"`
	RoundsPlayed int32       `json:"rounds_played"`
	Summary      []byte      `json:"summary"`
}

func (q *Queries) CreateGameResult(ctx context.Context, arg CreateGameResultParams) (GameResult, error) {
	row := q.db.QueryRow(ctx, createGameResult,
		arg.MatchID,
		arg.GameType,
		arg.RoundsPlayed,
		arg.Summary,
	)
	var i GameResult
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.GameType,
		&i.RoundsPlayed,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    room_id,
    game_type,
    status,
    metadata
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, room_id, game_type, status, winner_id, started_at, ended_at, duration_seconds, metadata
`

type CreateMatchParams struct {
	RoomID   pgtype.UUID `json:"room_id"`
	GameType string      `json:"game_type"`
	Status   string      `json:"status"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.RoomID,
		arg.GameType,
		arg.Status,
		arg.Metadata,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameType,
		&i.Status,
		&i.WinnerID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Metadata,
	)
	return i, err
}

const getGameResultByMatchID = `-- name: GetGameResultByMatchID :one
SELECT id, match_id, game_type, rounds_played, summary, created_at
FROM game_results
WHERE match_id = $1 LIMIT 1
`

func (q *Queries) GetGameResultByMatchID(ctx context.Context, matchID pgtype.UUID) (GameResult, error) {
	row := q.db.QueryRow(ctx, getGameResultByMatchID, matchID)
	var i GameResult
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.GameType,
		&i.RoundsPlayed,
		&i.Summary,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, room_id, game_type, status, winner_id, started_at, ended_at, duration_seconds, metadata
FROM matches
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.GameType,
		&i.Status,
		&i.WinnerID,
		&i.StartedAt,
		&i.EndedAt,
		&i.DurationSeconds,
		&i.Metadata,
	)
	return i, err
}

const getMatchPlayers = `-- name: GetMatchPlayers :many
SELECT mp.id, mp.match_id, mp.user_id, mp.player_index, mp.score, mp.is_winner, mp.rating_before, mp.rating_after, mp.created_at,
       u.username, p.avatar_preset
FROM match_players mp
JOIN users u ON mp.user_id = u.id
JOIN profiles p ON mp.user_id = p.user_id
WHERE mp.match_id = $1
ORDER BY mp.player_index ASC
`

type GetMatchPlayersRow struct {
	ID           pgtype.UUID        `json:"id"`
	MatchID      pgtype.UUID        `json:"match_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PlayerIndex  int32              `json:"player_index"`
	Score        int32              `json:"score"`
	IsWinner     bool               `json:"is_winner"`
	RatingBefore int32              `json:"rating_before"`
	RatingAfter  int32              `json:"rating_after"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Username     string             `json:"username"`
	AvatarPreset string             `json:"avatar_preset"`
}

func (q *Queries) GetMatchPlayers(ctx context.Context, matchID pgtype.UUID) ([]GetMatchPlayersRow, error) {
	rows, err := q.db.Query(ctx, getMatchPlayers, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMatchPlayersRow{}
	for rows.Next() {
		var i GetMatchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.UserID,
			&i.PlayerIndex,
			&i.Score,
			&i.IsWinner,
			&i.RatingBefore,
			&i.RatingAfter,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarPreset,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
