// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GameResult struct {
	ID           pgtype.UUID        `json:"id"`
	MatchID      pgtype.UUID        `json:"match_id"`
	GameType     string             `json:"game_type"`
	RoundsPlayed int32              `json:"rounds_played"`
	Summary      []byte             `json:"summary"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Match struct {
	ID              pgtype.UUID        `json:"id"`
	RoomID          pgtype.UUID        `json:"room_id"`
	GameType        string             `json:"game_type"`
	Status          string             `json:"status"`
	WinnerID        pgtype.UUID        `json:"winner_id"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	Metadata        []byte             `json:"metadata"`
}

type MatchPlayer struct {
	ID           pgtype.UUID        `json:"id"`
	MatchID      pgtype.UUID        `json:"match_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PlayerIndex  int32              `json:"player_index"`
	Score        int32              `json:"score"`
	IsWinner     bool               `json:"is_winner"`
	RatingBefore int32              `json:"rating_before"`
	RatingAfter  int32              `json:"rating_after"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Nickname     string             `json:"nickname"`
	AvatarPreset string             `json:"avatar_preset"`
	Title        string             `json:"title"`
	Bio          string             `json:"bio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Rating struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	GameType      string             `json:"game_type"`
	Rating        int32              `json:"rating"`
	Wins          int32              `json:"wins"`
	Losses        int32              `json:"losses"`
	Draws         int32              `json:"draws"`
	WinStreak     int32              `json:"win_streak"`
	BestWinStreak int32              `json:"best_win_streak"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID         pgtype.UUID        `json:"id"`
	Code       string             `json:"code"`
	GameType   string             `json:"game_type"`
	Title      string             `json:"title"`
	HostID     pgtype.UUID        `json:"host_id"`
	Status     string             `json:"status"`
	MaxPlayers int32              `json:"max_players"`
	IsPrivate  bool               `json:"is_private"`
	Passcode   pgtype.Text        `json:"passcode"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	IsGuest      bool               `json:"is_guest"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
