// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMatchPlayer(ctx context.Context, arg AddMatchPlayerParams) (MatchPlayer, error)
	CompleteMatch(ctx context.Context, arg CompleteMatchParams) (Match, error)
	CreateGameResult(ctx context.Context, arg CreateGameResultParams) (GameResult, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteRoom(ctx context.Context, code string) error
	GetGameResultByMatchID(ctx context.Context, matchID pgtype.UUID) (GameResult, error)
	GetLeaderboardByGame(ctx context.Context, arg GetLeaderboardByGameParams) ([]GetLeaderboardByGameRow, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (Match, error)
	GetMatchPlayers(ctx context.Context, matchID pgtype.UUID) ([]GetMatchPlayersRow, error)
	GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (GetProfileByUserIDRow, error)
	GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error)
	GetUserAllRatings(ctx context.Context, userID pgtype.UUID) ([]Rating, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRating(ctx context.Context, arg GetUserRatingParams) (Rating, error)
	ListActiveRooms(ctx context.Context) ([]ListActiveRoomsRow, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
	UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (UpdateRoomStatusRow, error)
	UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error)
}

var _ Querier = (*Queries)(nil)
