// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLeaderboardByGame = `-- name: GetLeaderboardByGame :many
SELECT r.id, r.user_id, r.game_type, r.rating, r.wins, r.losses, r.draws, r.win_streak, r.best_win_streak,
       u.username, p.nickname, p.avatar_preset, p.title
FROM ratings r
JOIN users u ON r.user_id = u.id
JOIN profiles p ON r.user_id = p.user_id
WHERE r.game_type = $1
ORDER BY r.rating DESC, r.wins DESC
LIMIT $2
`

type GetLeaderboardByGameParams struct {
	GameType string `json:"game_type"`
	Limit    int32  `json:"limit"`
}

type GetLeaderboardByGameRow struct {
	ID            pgtype.UUID `json:"id"`
	UserID        pgtype.UUID `json:"user_id"`
	GameType      string      `json:"game_type"`
	Rating        int32       `json:"rating"`
	Wins          int32       `json:"wins"`
	Losses        int32       `json:"losses"`
	Draws         int32       `json:"draws"`
	WinStreak     int32       `json:"win_streak"`
	BestWinStreak int32       `json:"best_win_streak"`
	Username      string      `json:"username"`
	Nickname      string      `json:"nickname"`
	AvatarPreset  string      `json:"avatar_preset"`
	Title         string      `json:"title"`
}

func (q *Queries) GetLeaderboardByGame(ctx context.Context, arg GetLeaderboardByGameParams) ([]GetLeaderboardByGameRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboardByGame, arg.GameType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLeaderboardByGameRow{}
	for rows.Next() {
		var i GetLeaderboardByGameRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameType,
			&i.Rating,
			&i.Wins,
			&i.Losses,
			&i.Draws,
			&i.WinStreak,
			&i.BestWinStreak,
			&i.Username,
			&i.Nickname,
			&i.AvatarPreset,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAllRatings = `-- name: GetUserAllRatings :many
SELECT id, user_id, game_type, rating, wins, losses, draws, win_streak, best_win_streak, updated_at
FROM ratings
WHERE user_id = $1
ORDER BY game_type ASC
`

func (q *Queries) GetUserAllRatings(ctx context.Context, userID pgtype.UUID) ([]Rating, error) {
	rows, err := q.db.Query(ctx, getUserAllRatings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rating{}
	for rows.Next() {
		var i Rating
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GameType,
			&i.Rating,
			&i.Wins,
			&i.Losses,
			&i.Draws,
			&i.WinStreak,
			&i.BestWinStreak,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRating = `-- name: GetUserRating :one
SELECT id, user_id, game_type, rating, wins, losses, draws, win_streak, best_win_streak, updated_at
FROM ratings
WHERE user_id = $1 AND game_type = $2 LIMIT 1
`

type GetUserRatingParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	GameType string      `json:"game_type"`
}

func (q *Queries) GetUserRating(ctx context.Context, arg GetUserRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, getUserRating, arg.UserID, arg.GameType)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameType,
		&i.Rating,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.WinStreak,
		&i.BestWinStreak,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRating = `-- name: UpsertRating :one
INSERT INTO ratings (
    user_id,
    game_type,
    rating,
    wins,
    losses,
    draws,
    win_streak,
    best_win_streak,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
)
ON CONFLICT (user_id, game_type) DO UPDATE
SET rating = EXCLUDED.rating,
    wins = EXCLUDED.wins,
    losses = EXCLUDED.losses,
    draws = EXCLUDED.draws,
    win_streak = EXCLUDED.win_streak,
    best_win_streak = GREATEST(ratings.best_win_streak, EXCLUDED.best_win_streak),
    updated_at = NOW()
RETURNING id, user_id, game_type, rating, wins, losses, draws, win_streak, best_win_streak, updated_at
`

type UpsertRatingParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	GameType      string      `json:"game_type"`
	Rating        int32       `json:"rating"`
	Wins          int32       `json:"wins"`
	Losses        int32       `json:"losses"`
	Draws         int32       `json:"draws"`
	WinStreak     int32       `json:"win_streak"`
	BestWinStreak int32       `json:"best_win_streak"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) (Rating, error) {
	row := q.db.QueryRow(ctx, upsertRating,
		arg.UserID,
		arg.GameType,
		arg.Rating,
		arg.Wins,
		arg.Losses,
		arg.Draws,
		arg.WinStreak,
		arg.BestWinStreak,
	)
	var i Rating
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GameType,
		&i.Rating,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.WinStreak,
		&i.BestWinStreak,
		&i.UpdatedAt,
	)
	return i, err
}
