// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    code,
    game_type,
    title,
    host_id,
    status,
    max_players,
    is_private,
    passcode
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, code, game_type, title, host_id, status, max_players, is_private, passcode, created_at, updated_at
`

type CreateRoomParams struct {
	Code       string      `json:"code"`
	GameType   string      `json:"game_type"`
	Title      string      `json:"title"`
	HostID     pgtype.UUID `json:"host_id"`
	Status     string      `json:"status"`
	MaxPlayers int32       `json:"max_players"`
	IsPrivate  bool        `json:"is_private"`
	Passcode   pgtype.Text `json:"passcode"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.Code,
		arg.GameType,
		arg.Title,
		arg.HostID,
		arg.Status,
		arg.MaxPlayers,
		arg.IsPrivate,
		arg.Passcode,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameType,
		&i.Title,
		&i.HostID,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.Passcode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM rooms
WHERE code = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteRoom, code)
	return err
}

const getRoomByCode = `-- name: GetRoomByCode :one
SELECT r.id, r.code, r.game_type, r.title, r.host_id, r.status, r.max_players, r.is_private, r.passcode, r.created_at, r.updated_at,
       u.username AS host_username, p.avatar_preset AS host_avatar
FROM rooms r
JOIN users u ON r.host_id = u.id
JOIN profiles p ON r.host_id = p.user_id
WHERE r.code = $1 LIMIT 1
`

type GetRoomByCodeRow struct {
	ID           pgtype.UUID        `json:"id"`
	Code         string             `json:"code"`
	GameType     string             `json:"game_type"`
	Title        string             `json:"title"`
	HostID       pgtype.UUID        `json:"host_id"`
	Status       string             `json:"status"`
	MaxPlayers   int32              `json:"max_players"`
	IsPrivate    bool               `json:"is_private"`
	Passcode     pgtype.Text        `json:"passcode"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	HostUsername string             `json:"host_username"`
	HostAvatar   string             `json:"host_avatar"`
}

func (q *Queries) GetRoomByCode(ctx context.Context, code string) (GetRoomByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoomByCode, code)
	var i GetRoomByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameType,
		&i.Title,
		&i.HostID,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.Passcode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HostUsername,
		&i.HostAvatar,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT r.id, r.code, r.game_type, r.title, r.host_id, r.status, r.max_players, r.is_private, r.created_at, r.updated_at,
       u.username AS host_username, p.avatar_preset AS host_avatar
FROM rooms r
JOIN users u ON r.host_id = u.id
JOIN profiles p ON r.host_id = p.user_id
WHERE r.is_private = FALSE AND r.status != 'completed' AND r.status != 'cancelled'
ORDER BY r.created_at DESC
LIMIT 50
`

type ListActiveRoomsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Code         string             `json:"code"`
	GameType     string             `json:"game_type"`
	Title        string             `json:"title"`
	HostID       pgtype.UUID        `json:"host_id"`
	Status       string             `json:"status"`
	MaxPlayers   int32              `json:"max_players"`
	IsPrivate    bool               `json:"is_private"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	HostUsername string             `json:"host_username"`
	HostAvatar   string             `json:"host_avatar"`
}

func (q *Queries) ListActiveRooms(ctx context.Context) ([]ListActiveRoomsRow, error) {
	rows, err := q.db.Query(ctx, listActiveRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRoomsRow{}
	for rows.Next() {
		var i ListActiveRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.GameType,
			&i.Title,
			&i.HostID,
			&i.Status,
			&i.MaxPlayers,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HostUsername,
			&i.HostAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoomStatus = `-- name: UpdateRoomStatus :one
UPDATE rooms
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, code, game_type, title, host_id, status, max_players, is_private, updated_at
`

type UpdateRoomStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

type UpdateRoomStatusRow struct {
	ID         pgtype.UUID        `json:"id"`
	Code       string             `json:"code"`
	GameType   string             `json:"game_type"`
	Title      string             `json:"title"`
	HostID     pgtype.UUID        `json:"host_id"`
	Status     string             `json:"status"`
	MaxPlayers int32              `json:"max_players"`
	IsPrivate  bool               `json:"is_private"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateRoomStatus(ctx context.Context, arg UpdateRoomStatusParams) (UpdateRoomStatusRow, error) {
	row := q.db.QueryRow(ctx, updateRoomStatus, arg.ID, arg.Status)
	var i UpdateRoomStatusRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GameType,
		&i.Title,
		&i.HostID,
		&i.Status,
		&i.MaxPlayers,
		&i.IsPrivate,
		&i.UpdatedAt,
	)
	return i, err
}
