// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    user_id,
    nickname,
    avatar_preset,
    title,
    bio
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, nickname, avatar_preset, title, bio, created_at, updated_at
`

type CreateProfileParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Nickname     string      `json:"nickname"`
	AvatarPreset string      `json:"avatar_preset"`
	Title        string      `json:"title"`
	Bio          string      `json:"bio"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.UserID,
		arg.Nickname,
		arg.AvatarPreset,
		arg.Title,
		arg.Bio,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.AvatarPreset,
		&i.Title,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password_hash,
    is_guest
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, username, email, is_guest, created_at, updated_at
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"password_hash"`
	IsGuest      bool        `json:"is_guest"`
}

type CreateUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	IsGuest   bool               `json:"is_guest"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.IsGuest,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsGuest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfileByUserID = `-- name: GetProfileByUserID :one
SELECT p.id, p.user_id, p.nickname, p.avatar_preset, p.title, p.bio, p.created_at, p.updated_at,
       u.username, u.email, u.is_guest
FROM profiles p
JOIN users u ON p.user_id = u.id
WHERE p.user_id = $1 LIMIT 1
`

type GetProfileByUserIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Nickname     string             `json:"nickname"`
	AvatarPreset string             `json:"avatar_preset"`
	Title        string             `json:"title"`
	Bio          string             `json:"bio"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	Email        pgtype.Text        `json:"email"`
	IsGuest      bool               `json:"is_guest"`
}

func (q *Queries) GetProfileByUserID(ctx context.Context, userID pgtype.UUID) (GetProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i GetProfileByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.AvatarPreset,
		&i.Title,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Email,
		&i.IsGuest,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, is_guest, created_at, updated_at
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsGuest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, is_guest, created_at, updated_at
FROM users
WHERE id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Email     pgtype.Text        `json:"email"`
	IsGuest   bool               `json:"is_guest"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsGuest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, is_guest, created_at, updated_at
FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsGuest,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET nickname = $2,
    avatar_preset = $3,
    title = $4,
    bio = $5,
    updated_at = NOW()
WHERE user_id = $1
RETURNING id, user_id, nickname, avatar_preset, title, bio, created_at, updated_at
`

type UpdateProfileParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	Nickname     string      `json:"nickname"`
	AvatarPreset string      `json:"avatar_preset"`
	Title        string      `json:"title"`
	Bio          string      `json:"bio"`
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.UserID,
		arg.Nickname,
		arg.AvatarPreset,
		arg.Title,
		arg.Bio,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nickname,
		&i.AvatarPreset,
		&i.Title,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
